import { useState } from 'react';
import { Typography, Pagination as MuiPagination } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { reportsService } from '@/services/reports.service';
import { ReportHistoryTable } from '@/features/reports/ReportHistoryTable';
import { ReportViewerFilters } from '@/features/reports/ReportViewerFilters';
import { ReportPreviewDialog } from '@/features/reports/ReportPreviewDialog';

export default function ReportViewerReportsPage() {
  const [userId, setUserId] = useState<string | undefined>(undefined);
  const [page, setPage] = useState(1);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewReportId, setPreviewReportId] = useState<string | null>(null);

  const { data: generators = [] } = useQuery({
    queryKey: ['report-generators'],
    queryFn: () => reportsService.getGenerators(),
  });

  const { data, isLoading } = useQuery({
    queryKey: ['reports-history', userId, page],
    queryFn: () => reportsService.getHistory(page, 20, userId),
    placeholderData: (prev) => prev,
  });

  const handleSelect = (id: string) => {
    setPreviewReportId(id);
    setPreviewOpen(true);
  };

  return (
    <div className="flex flex-col gap-4">
      <div>
        <Typography variant="h5" className="font-semibold text-charcoal">
          Reports
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Review and download reports generated by the operations team
        </Typography>
      </div>

      <ReportViewerFilters
        generators={generators}
        onApply={(id) => {
          setUserId(id);
          setPage(1);
        }}
      />

      <ReportHistoryTable reports={data?.items ?? []} loading={isLoading} onSelect={handleSelect} />

      {data && data.pagination.totalPages > 1 && (
        <div className="flex justify-center">
          <MuiPagination
            count={data.pagination.totalPages}
            page={data.pagination.page}
            onChange={(_, p) => setPage(p)}
            color="primary"
          />
        </div>
      )}

      <ReportPreviewDialog open={previewOpen} onClose={() => setPreviewOpen(false)} reportId={previewReportId} />
    </div>
  );
}