import { Table, TableHead, TableBody, TableRow, TableCell, Chip, Paper, Skeleton } from '@mui/material';
import dayjs from 'dayjs';
import type { ReportHistoryItem } from '@/services/reports.service';

interface Props {
  reports: ReportHistoryItem[];
  loading?: boolean;
  onSelect: (id: string) => void;
}

export function ReportHistoryTable({ reports, loading, onSelect }: Props) {
  if (loading) {
    return (
      <Paper elevation={0} className="p-4 rounded-card border border-gray-200">
        <div className="flex flex-col gap-2">
          {[1, 2, 3, 4].map((i) => (
            <Skeleton key={i} variant="rounded" height={40} />
          ))}
        </div>
      </Paper>
    );
  }

  if (reports.length === 0) {
    return (
      <Paper elevation={0} className="p-8 rounded-card border border-gray-200 text-center">
        <p className="text-cool-gray text-sm">No reports match your filters.</p>
      </Paper>
    );
  }

  return (
    <Paper elevation={0} className="rounded-card border border-gray-200 overflow-hidden">
      <Table size="small">
        <TableHead>
          <TableRow className="bg-slate-gray">
            <TableCell className="font-semibold">Report</TableCell>
            <TableCell className="font-semibold">Generated By</TableCell>
            <TableCell className="font-semibold">Format</TableCell>
            <TableCell className="font-semibold">Date</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {reports.map((report) => (
            <TableRow key={report.id} hover className="cursor-pointer" onClick={() => onSelect(report.id)}>
              <TableCell>{report.type.replace(/-/g, ' ')}</TableCell>
              <TableCell>
                {report.generatedByUser.firstName} {report.generatedByUser.lastName}
              </TableCell>
              <TableCell>
                <Chip label={report.format} size="small" variant="outlined" />
              </TableCell>
              <TableCell>{dayjs(report.createdAt).format('MMM D, YYYY · h:mm A')}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Paper>
  );
}